swagger: '2.0'
info:
  version: 1.0.0
  title: OrderApi
schemes:
  - https
paths:
  /order:
    get:
      summary: returns a list of orders
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/orderList'
    post:
      summary: Add a new order
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: orderData
          in: body
          description: data to create an order
          required: true
          schema:
            $ref: '#/definitions/orderInput'
      responses:
        '201':
          description: successful operation
          schema:
            $ref: '#/definitions/orderDetails'
        '400':
          description: Incorrect input
        '403':
          description: Not allowed to create an order
        '500':
          description: Internal server error
  '/order/{orderId}':
    get:
      summary: returns the order details
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: the order-id
          required: true
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/orderDetails'
    delete:
      summary: deletes the order
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: the order-id
          required: true
          type: string
          format: uuid
      responses:
        '200':
          description: OK
        '403':
          description: Not allowed to delete this order
  '/order/user/{userId}':
    get:
      summary: return a list of orders of a specific user
      produces:
        - application/json
      parameters:
        - name: userId
          in: path
          description: the user-id
          required: true
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/orderList'
definitions:
  orderList:
    type: array
    items:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        price:
          type: number
        orderedOn:
          type: string
          format: date
        isPayed:
          type: boolean
        _links:
          type: object
          properties:
            self:
              type: string
              format: uri
  orderDetails:
    type: object
    properties:
      price:
        type: number
      orderedOn:
        type: string
        format: date
      isPayed:
        type: boolean
      _links:
        type: object
        properties:
          self:
            type: string
            format: uri
          user:
            type: string
            format: uri
          event:
            type: string
            format: uri
  orderInput:
    type: object
    properties:
      userId:
        type: string
        format: uuid
      events:
        type: array
        items:
          type: object
          properties:
            event-uuid:
              type: string
              format: uuid
